kind: Service
apiVersion: v1
metadata:
  name: confluent-kafka01-monitor
  namespace: confluent
spec:
  ports:
  - name: port-10998
    port: 10998
    protocol: TCP 
  selector:
    app: confluent-kafka01
---
apiVersion: v1
kind: Service
metadata:
  name: confluent-kafka01
  namespace: confluent
spec:
  type: LoadBalancer
  externalIPs:
    - 10.0.15.101
  ports:
    - name: port-9092
      port: 9092
      nodePort: 30061
      protocol: TCP
  selector:
    app: confluent-kafka01
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: confluent-kafka01
  namespace: confluent
spec:
  selector:
    matchLabels:
      app: confluent-kafka01
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: confluent-kafka01
    spec:
      containers:
      - name: confluent-kafka01
        image: docker.registry.local:5000/confluent-kafka01:v1.${BUILD_NUMBER}
        ports:
        - containerPort: 9092
        - containerPort: 9090
        - containerPort: 10998
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "confluent-zoo01:2181,confluent-zoo02:2181,confluent-zoo03:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "10.0.15.101:30061"





