kind: Service
apiVersion: v1
metadata:
  name: confluent-kafka01-monitor
  namespace: confluent
spec:
  ports:
  - name: port-10998
    port: 10998
    protocol: TCP 
  selector:
    app: confluent-kafka01
---
apiVersion: v1
kind: Service
metadata:
  name: confluent-kafka01
  namespace: confluent
spec:
  type: LoadBalancer
  externalIPs:
    - 10.0.15.101
  ports:
    - name: port-9092
      port: 9092
      nodePort: 30061
      protocol: TCP
  selector:
    app: confluent-kafka01
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: confluent-kafka01
  namespace: confluent
spec:
  selector:
    matchLabels:
      app: confluent-kafka01
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: confluent-kafka01
    spec:
      containers:
      - name: confluent-kafka01
        image: docker.registry.local:5000/confluent-kafka01:v1.${BUILD_NUMBER}
        ports:
        - containerPort: 9092
        - containerPort: 9090
        - containerPort: 10998
        env:
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTERNAL:SASL_SSL,EXTERNAL:SASL_SSL"
        - name: KAFKA_LISTENERS
          value: "INTERNAL://confluent-kafka01:9092,EXTERNAL://:9090"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INTERNAL://confluent-kafka01:9092,EXTERNAL://10.0.15.101:6001"
        - name: KAFKA_inter_broker_listener_name
          value: "INTERNAL"
        - name: KAFKA_delete.topic.enable
          value: "true"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "confluent-zoo01:2181,confluent-zoo02:2181,confluent-zoo03:2181"
        - name: KAFKA_log_dirs
          value: "/var/lib/kafka/data"
        - name: KAFKA_broker_id
          value: "1"
        - name: KAFKA_cruise_control_metrics_reporter_topic_replicas
          value: "3"
        - name: KAFKA_cruise_control_metrics_reporter_bootstrap_servers
          value: "confluent-kafka01:9092"
        - name: KAFKA_log_retention_hours
          value: "168"
        - name: KAFKA_num_partitions
          value: "1"
        - name: KAFKA_authorizer_class_name
          value: "kafka.security.auth.SimpleAclAuthorizer"
        - name: KAFKA_super_users
          value: "User:client;User:admin"
        - name: KAFKA_allow_everyone_if_no_acl_found
          value: "true"
        - name: KAFKA_cruise_control_metrics_reporter_security_protocol
          value: "SASL_SSL"
        - name: KAFKA_ssl_truststore_location
          value: "/var/ssl/private/client_truststore_jks"
        - name: KAFKA_ssl_truststore_password
          value: "confluent"
        - name: KAFKA_ssl_keystore_location
          value: "/var/ssl/private/client_keystore_jks"
        - name: KAFKA_ssl_keystore_password
          value: "confluent"
        - name: KAFKA_ssl_key_password
          value: "confluent"
        - name: KAFKA_ssl_client_auth
          value: "required"
        - name: KAFKA_cruise_control_metrics_reporter_ssl_truststore_location
          value: "/var/ssl/private/client_truststore_jks"
        - name: KAFKA_cruise_control_metrics_reporter_ssl_truststore_password
          value: "confluent"
        - name: KAFKA_cruise_control_metrics_reporter_ssl_keystore_location
          value: "/var/ssl/private/client_keystore_jks"
        - name: KAFKA_cruise_control_metrics_reporter_ssl_keystore_password
          value: "confluent"
        - name: KAFKA_cruise_control_metrics_reporter_ssl_key_password
          value: "confluent"
        - name: KAFKA_sasl_enabled_mechanisms
          value: "PLAIN"
        - name: KAFKA_sasl_mechanism_inter_broker_protocol
          value: "PLAIN"
        - name: KAFKA_cruise_control_metrics_reporter_sasl_mechanism
          value: "PLAIN"
        - name: KAFKA_cruise_control_metrics_reporter_sasl_jaas_config
          value: "org.apache.kafka.common.security.plain.PlainLoginModule required username=client password=client-secret"
        - name: KAFKA_confluent_support_metrics_enable
          value: "false"
        - name: KAFKA_confluent_support_customer_id
          value: "anonymous"









